PIH/openmrs-module-pihmalawi

api/src/main/java/org/openmrs/module/pihmalawi/reporting/ApzuReportUtil.java
api/src/main/java/org/openmrs/module/pihmalawi/reporting/definition/data/evaluator/DiagnosesBasedOnMastercardsPatientDataEvaluator.java
api/src/main/java/org/openmrs/module/pihmalawi/reporting/definition/renderer/IC3TraceReportRenderer.java
omod/src/main/webapp/resources/htmlforms/htn_dm_mastercard.xml

I entered the correct concept id for Hypertension and formatted the due dates of the report.

MLW-357, correct the htn_dm mastercard

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/EncounterTypes.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/EncounterTypeBundle.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/ChronicHeartFailureConcepts.java
omod/src/main/java/org/openmrs/module/pihmalawi/web/taglibs/EMastercardAccessTag.java
omod/src/main/webapp/portlets/malawiPatientDashboard.jsp
omod/src/main/webapp/resources/htmlforms/chf_annual_screening.xml
omod/src/main/webapp/resources/htmlforms/chf_history_of_hospitalizations.xml
omod/src/main/webapp/resources/htmlforms/chf_mastercard.xml
omod/src/main/webapp/resources/htmlforms/chf_quarterly_screening.xml
omod/src/main/webapp/resources/htmlforms/chf_visit.xml

- A collection of the forms for the CHF mastercard
- Some new concepts
- Some new encounters
- And updating the patient dashborad

MLW-707, Chronic Heart Failure (CHF) eMasterCard

---

README.md

Just testing pull request for a branch

MLW-716, test PR with branch

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/ChronicKidneyDiseaseConcepts.java
omod/src/main/webapp/resources/htmlforms/ckd_mastercard.xml
omod/src/main/webapp/resources/htmlforms/ckd_visit.xml

- Removed "unknown" as an option in the HIV status section of the header.
- Removed "FSB/HBA1c" from the visit form.
- Added concept glomerular filtration rate (GFR) test to the visit form (mL/min).

MLW-716, Modifications to the CKD mastercard

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/ChronicHeartFailureConcepts.java

- added **_unknown_** and **_valvular_** as options to heart  diagnoses.

MLW-707 additional answer concepts to chronic heart failure diagnosis

---

api/src/main/java/org/openmrs/module/pihmalawi/activator/HtmlFormInitializer.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/EncounterTypes.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/EncounterTypeBundle.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/AdvancedNCDMastercardConcepts.java
omod/src/main/java/org/openmrs/module/pihmalawi/web/taglibs/EMastercardAccessTag.java
omod/src/main/webapp/portlets/malawiPatientDashboard.jsp
omod/src/main/webapp/resources/htmlforms/ancd_annual_screening.xml
omod/src/main/webapp/resources/htmlforms/ancd_hospitalizations.xml
omod/src/main/webapp/resources/htmlforms/ancd_mastercard.xml
omod/src/main/webapp/resources/htmlforms/ancd_quarterly_screening.xml
omod/src/main/webapp/resources/htmlforms/ancd_visit.xml

- Generic eMastercarcd for the advanced NCD clinic

MLW-830, generic mastercard for advaced NCD

---

omod/src/main/webapp/resources/htmlforms/htn_dm_visit.xml
omod/src/main/webapp/resources/scripts/mastercard.js

Hi @pochedls , I stole your code and just arranged similar to validateAppointmentDate function. Now, I think the validation of HbA1c field works as we want it by disabling the form's Submit button too. Please have a look and let me know what you think. Thanks!

MLW-1131, validate HbA1c field

---

omod/src/main/webapp/resources/scripts/mastercard.js

I think this will address MLW-1139 - sorry I didn't catch this earlier.

Fix for MLW-1139

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/VersionedPihConceptBundle.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/CoreConceptMetadataBundle.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/MasterCardConcepts.java

Hi Cosmin, 
I have an issue with installing one of the concepts (a convSet) for drug dispensing. I have commented out the last troublesome concept. 
Let me know what you think. 
Thanks.

MLW-1138, Add new concepts for drug dispensing

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/IC3TraceReportRestController.java
omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/YendaNafePatientRestController.java

hello @cioan 
Please review the code, have added for each request to the Trace and YendaNafe registration to be returning the result with the appropriate HTTP status code.
cc: @tlimbani

MLW-1146-Add response HTTP status codes for requests

---

api/src/main/java/org/openmrs/module/pihmalawi/activator/HtmlFormInitializer.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/EncounterTypes.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/EncounterTypeBundle.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/PihMalawiMetadataBundle.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/TraceConcepts.java
api/src/main/resources/messages.properties
omod/src/main/java/org/openmrs/module/pihmalawi/web/taglibs/ETraceAccessTag.java
omod/src/main/webapp/portlets/malawiPatientDashboard.jsp
omod/src/main/webapp/resources/htmlforms/trace_mastercard.xml
omod/src/main/webapp/resources/htmlforms/trace_visit.xml
omod/src/main/webapp/taglib/pihmalawi.tld

Hi @tlimbani , @kmatiya and @mseaton , just wanted to give you a quick update on the direction I started with capturing the Trace attempts in EMR. I will add more details in the JIRA to the MLW-1158 ticket, but this the PR.

MLW-1158, add trace encounter and forms to track trace attempts

---

omod/src/main/webapp/resources/htmlforms/art_visit.xml

Hi @kmatiya, here is my first attempt on validating those fields. I think there are still some gaps, but let me know what you think. Thanks!

MLW-1162, validate pill count and ART regimen selection

---

api/src/test/java/org/openmrs/module/pihmalawi/reporting/reports/IC3DataEntryTest.java
omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/IC3DataEntryRestController.java
omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/IC3TraceReportRestController.java

Added endpoint for accessing data entry report and included labWeeks parameter when querying trace report for end point
@tlimbani review and merge

Additions to MLW-1146 and MLW-1160

---

api/src/main/resources/org/openmrs/module/pihmalawi/reporting/datasets/sql/appointment-data-entry-data.sql

@cioan You can merge this and later update on the servers when updating for ticket MLW-1178

MLW-1160 Include HCC Number when compiling data entry report

---

api/src/main/java/org/openmrs/module/pihmalawi/activator/HtmlFormInitializer.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/EncounterTypes.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/PdcMetadata.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/PihMalawiPatientIdentifierTypes.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/EncounterTypeBundle.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/PatientIdentifierBundle.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/PihMalawiMetadataBundle.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/PdcConcepts.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/ProgramConcepts.java
omod/src/main/java/org/openmrs/module/pihmalawi/web/taglibs/EMastercardAccessTag.java
omod/src/main/webapp/portlets/malawiPatientDashboard.jsp
omod/src/main/webapp/resources/htmlforms/pdc_mastercard.xml
omod/src/main/webapp/resources/htmlforms/pdc_visit.xml

PDC program workflows and intake concepts
@tlimbani

MLW-1221- Add PDC program and its workflows concepts in the EMR

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/IC3ScreeningConcepts.java
api/src/main/resources/org/openmrs/module/pihmalawi/reporting/datasets/sql/appointment-data-entry-data.sql

Add "Zalewa GeneXpert" as lab location where a viral load test was done
cc: @tlimbani

Add Zalewa GeneXpert option for lab location

---

api/src/main/java/org/openmrs/module/pihmalawi/data/IC3ScreeningData.java
api/src/main/java/org/openmrs/module/pihmalawi/data/LivePatientDataSet.java
api/src/main/java/org/openmrs/module/pihmalawi/reporting/definition/dataset/evaluator/IC3AppointmentDataSetEvaluator.java
omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/IC3ScreeningRestController.java

Do these changes make sense, @mseaton ? Thanks!

MLW-1266, refactor reports

---

api/src/test/java/org/openmrs/module/pihmalawi/reporting/reports/RegimenDispensationReportTest.java

@cioan 
Have added test for MOH Regimen Dispensation Report . Report uses data warehouse.

MLW-1279 Add MOH Regimen Dispensation Report 

---

omod/src/main/webapp/resources/htmlforms/art_visit.xml

MLW-1350 Allow override on obs reference for height and weight at ART followup

---

.gitignore
api/src/main/java/org/openmrs/module/pihmalawi/reporting/definition/renderer/TraceReportRenderer.java
api/src/main/resources/org/openmrs/module/pihmalawi/reporting/datasets/sql/trace-data.sql

@tlimbani , this is the second part which adds the Visit Missed column to the Trace report.

MLW-1351, add last encounter type

---

omod/src/main/webapp/resources/htmlforms/pdc_other_diagnosis_visit.xml

@b-ngongonda. This has been fixed.

MWL-1372 - Fix concepts for age adjusted and unadjusted

---

omod/src/main/webapp/resources/htmlforms/pdc_developmental_delay_visit.xml

added weight against age obs group and weight against height group on numeric value concept

MLW-1356: added obs group on numeric value concept on developmental delay mastercard

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/MasterCardConcepts.java
omod/src/main/webapp/resources/htmlforms/art_visit.xml

MLW-1403: Add column for 3HP on ART mastercard followup

---

omod/src/main/webapp/resources/htmlforms/art_visit.xml

MLW-1403: Update RFP/INH column on art_visit mastercard

---

omod/src/main/webapp/resources/htmlforms/pdc_cleft_lip_palate_visit.xml

MLW-1425: Update Weight/Age and Weight/Height Concepts on PDC Cleft Lip Palate Visit Mastercard

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/MohRegimenDispensationByWeightReportRestController.java

This will help access the Report for easy analysis through third party systems (e.g PowerBI and scripting languages like Python and R).

MLW-1461 Add MoH Regimen Dispensation By Weight Report Rest Endpoint

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/MohRegimenDispenstionReportRestController.java

This will help access the MoH Regimen Switch Report for easy analysis through third party systems (e.g PowerBI and scripting languages like Python and R).

MLW-1462 Add MoH Regimen Dispensation Report Rest Endpoint

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/MohSurvivalAnalysisChildrenReportRestController.java

This will help access the MoH Regimen Switch Report for easy analysis through third party systems (e.g PowerBI and scripting languages like Python and R).

MLW-1463 Add MoH Survival Analysis Children Report Rest Endpoint

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/MohSurvivalAnalysisGeneralReportRestController.java

This will help access the MoH Regimen Switch Report for easy analysis through third party systems (e.g PowerBI and scripting languages like Python and R).

MLW-1464 Add MoH Survival Analysis General Report Rest Endpoint

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/MohSurvivalAnalysisOptionBReportRestController.java

MLW-1465 Add MoH Survival Analysis Option B Report Rest Endpoint

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/MohTptNewInitiationReportRestController.java

MLW-1466 Add MoH TPT New Initiation Report Rest Endpoint

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/MohTxCurrMmdReportRestController.java

MLW-1467 Add MoH TX Curr MMD Report Rest Endpoint

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/PepfarCohortDisaggregatedReportRestController.java

MLW-1468 Add PEPFAR Cohort Disaggregated Report Rest Endpoint

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/PepfarTxCurrMmdReportRestController.java

MLW-1469 Add PEPFAR TX Curr MMD Report Rest Endpoint

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/PepfarTxMlReportRestController.java

MLW-1470 Add PEPFAR TX ML Report Rest Endpoint

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/PepfarTxRttReportRestController.java

MLW-1471 Add PEPFAR TX RTT Report Rest Endpoint

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/MohRegimenDispensationByWeightReportRestController.java
omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/MohRegimenDispenstionReportRestController.java

MLW-1482: Update MOH Regimen Dispensation By Weight and MOH Regimen Dispenstion Reports Rest Controller

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/PepfarTbPrevReportRestController.java

MLW-1484: Expose PEPFAR TB Prev Report as REST End Point

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/NutritionConcepts.java

MLW-1493: Add Number of Lactogen tins concept

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/NutritionConcepts.java

MLW-1515: Add Nutrition Concepts

---

api/src/main/java/org/openmrs/module/pihmalawi/activator/HtmlFormInitializer.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/EncounterTypes.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/EncounterTypeBundle.java
omod/src/main/java/org/openmrs/module/pihmalawi/web/taglibs/EMastercardAccessTag.java
omod/src/main/webapp/portlets/malawiPatientDashboard.jsp
omod/src/main/webapp/resources/htmlforms/nutrition_mastercard.xml
omod/src/main/webapp/resources/htmlforms/nutrition_visit.xml

MLW-1520: Add Nutrition Program encounter metadata

---

omod/src/main/webapp/resources/htmlforms/nutrition_adults_mastercard.xml
omod/src/main/webapp/resources/htmlforms/nutrition_adults_visit.xml

MLW-1521: Add Adults Nutrition Initial Form

---

omod/src/main/webapp/resources/htmlforms/nutrition_infant_mastercard.xml
omod/src/main/webapp/resources/htmlforms/nutrition_infant_visit.xml
omod/src/main/webapp/resources/htmlforms/nutrition_pdc_mastercard.xml
omod/src/main/webapp/resources/htmlforms/nutrition_pdc_visit.xml
omod/src/main/webapp/resources/htmlforms/nutrition_pregnant_teens_mastercard.xml
omod/src/main/webapp/resources/htmlforms/nutrition_pregnant_teens_visit.xml

MLW-1522: Add Infant Nutrition Initial Form

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/MasterCardConcepts.java
omod/src/main/webapp/resources/htmlforms/mental_health_mastercard.xml
omod/src/main/webapp/resources/htmlforms/mental_health_visit.xml

MLW-1526: Update current mental health mastercard in the EMR to version 1.4 of the paper version

---

omod/src/main/webapp/resources/htmlforms/art_mastercard.xml

MLW-1527: Fix art mastercard variables

---

omod/src/main/webapp/resources/htmlforms/art_follow_up_testing.xml

This PR adds `location` and groups `serumGlucose` and `glucoseTestType` into an `obsgroup`.

MLW-1535, Update art follow up form

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/MasterCardConcepts.java
omod/src/main/webapp/resources/htmlforms/art_mastercard.xml

This PR adds Date of Urine Lam concept in openmrs.
@b-ngongonda PTAL.

MLW-1539: Add Date of Urine Lam concept

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/EncounterTypes.java

MLW-1543: fix encounters in the EncounterType file

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/MasterCardConcepts.java

This PR adds oil given to patient concept. The concept is numeric and the unit of measurement is liters.
@b-ngongonda @cioan PTAL.

MLW-1549: Add oil given to patient concept

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/NutritionConcepts.java
omod/src/main/webapp/resources/htmlforms/nutrition_pdc_visit.xml

MLW-1525: Update nutrition pdc visits followup mastercards

---

omod/src/main/webapp/portlets/malawiPatientDashboard.jsp

MLW-1547: updated teen club enrollment age restriction

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/ChronicHeartFailureConcepts.java
omod/src/main/webapp/resources/htmlforms/chf_annual_screening.xml
omod/src/main/webapp/resources/htmlforms/chf_visit.xml

MLW-1536: Update chronic heart failure mastercard version 3 in the EMR with missing details

---

omod/src/main/webapp/resources/htmlforms/ckd_visit.xml

MLW-1443: Chronic kidney disease followup form - add medication dosage and frequency

---

omod/src/main/webapp/resources/htmlforms/nutrition_adults_visit.xml
omod/src/main/webapp/resources/htmlforms/nutrition_infant_visit.xml
omod/src/main/webapp/resources/htmlforms/nutrition_pdc_visit.xml
omod/src/main/webapp/resources/htmlforms/nutrition_pregnant_teens_mastercard.xml
omod/src/main/webapp/resources/htmlforms/nutrition_pregnant_teens_visit.xml

MLW-1553: update nutrition patient mastercards

---

omod/src/main/webapp/resources/htmlforms/chf_annual_screening.xml
omod/src/main/webapp/resources/htmlforms/nutrition_pregnant_teens_visit.xml

MLW-1549: changed oil given variable from coded to numeric

---

omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/PepfarTxTbReportRestController.java

MLW-1564: Expose PEPFAR TX_TB Report as REST End Point

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/MasterCardConcepts.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/NutritionConcepts.java
omod/src/main/webapp/resources/htmlforms/nutrition_adults_visit.xml

MLW-1521: refactor Nutrition Adult's food concept

---

api/src/main/java/org/openmrs/module/pihmalawi/activator/PihMalawiModuleActivator.java
api/src/main/resources/liquibase.xml
configuration/configuration/liquibase/liquibase.xml
configuration/configuration/liquibase/sql/general_functions.sql
configuration/configuration/liquibase/sql/person_functions.sql
configuration/configuration/liquibase/sql/user_functions.sql
configuration/configuration/log4j2.xml
configuration/configuration/reports/reportdescriptors/sql/user_logins.sql
configuration/configuration/reports/reportdescriptors/sql/user_roles.sql
configuration/configuration/reports/reportdescriptors/sql/users.sql
configuration/configuration/reports/reportdescriptors/user_logins.yml
configuration/configuration/reports/reportdescriptors/user_roles.yml
configuration/configuration/reports/reportdescriptors/users.yml
pom.xml

Thanks @mseaton ! The Rwanda EMR code worked great for Malawi too.

MLW-1569:add user login reporting

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/MasterCardConcepts.java
omod/src/main/webapp/portlets/malawiPatientDashboard.jsp
omod/src/main/webapp/resources/htmlforms/sickle_cell_annual_screening.xml
omod/src/main/webapp/resources/htmlforms/sickle_cell_mastercard.xml
omod/src/main/webapp/resources/htmlforms/sickle_cell_quarterly_screening.xml
omod/src/main/webapp/resources/htmlforms/sickle_cell_visit.xml

MLW-1568: add missing observations on sickle cell mastercard

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/MasterCardConcepts.java

This PR updates Quantity of medication prescribed per dose concept to accept decimals.
@b-ngongonda PTAL

MLW-1574: Update medication dose concept to accept decimals

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/EncounterTypes.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/EncounterTypeBundle.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/TeenClubIntakeSurveyConcepts.java
omod/src/main/java/org/openmrs/module/pihmalawi/web/taglibs/EMastercardAccessTag.java
omod/src/main/webapp/resources/htmlforms/teen_club_intake_survey.xml

This PR adds mUzima to OpenMRS.
1. It introduces new concepts that are used in the teen club intake survey.
2. Create a form for the teen club intake survey in OpenMRS.
@b-ngongonda PTAL

Add mUzima to OpenMRS

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/TeenClubConcepts.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/TeenClubIntakeSurveyConcepts.java
omod/src/main/webapp/resources/htmlforms/teen_club_visit.xml

MLW-1584: Update teen club screening form

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/TeenClubIntakeSurveyConcepts.java
omod/src/main/webapp/resources/htmlforms/teen_club_intake_survey.xml

This creates new concepts that are used in the teen club intake form in OpenMRS.
@b-ngongonda PTAL.

Fix Teen Club Intake Survey failing to load

---

omod/src/main/webapp/resources/htmlforms/sickle_cell_mastercard.xml
omod/src/main/webapp/resources/htmlforms/sickle_cell_visit.xml

MLW-1568: update lung and conjunctiva variables on sickle cell visit

---

api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/TeenClubIntakeSurveyConcepts.java
omod/src/main/webapp/resources/htmlforms/teen_club_intake_survey.xml

This PR adds concepts for newly added questions on the teen club intake survey and updates the OpenMRS form with the concepts.
@b-ngongonda PTAL.

Add concepts and update openmrs form

---

omod/src/main/webapp/resources/htmlforms/art_mastercard.xml

MLW-1620: Add field for patient phone number on the ART mastercard

---

api/src/main/resources/org/openmrs/module/pihmalawi/reporting/datasets/sql/moh-tx-mmd.sql
api/src/main/resources/org/openmrs/module/pihmalawi/reporting/datasets/sql/pepfar-tx-mmd.sql
api/src/main/resources/org/openmrs/module/pihmalawi/reporting/datasets/sql/pepfar-tx_pvls.sql
api/src/main/resources/org/openmrs/module/pihmalawi/reporting/datasets/sql/tb_prev.sql

MLW-1587: refactor pepfar tx_pvls, tx_mmd and tb_prev reports

---

api/src/main/java/org/openmrs/module/pihmalawi/alert/AlertEngine.java
api/src/main/java/org/openmrs/module/pihmalawi/metadata/deploy/bundle/concept/MasterCardConcepts.java
api/src/main/java/org/openmrs/module/pihmalawi/provider/VhwProviderIdentifierGenerator.java
api/src/main/resources/org/openmrs/module/pihmalawi/alert/functions.js
api/src/test/java/org/openmrs/module/pihmalawi/alert/AlertEngineTest.java
pom.xml

Attempting to upgrade the depending modules.

MLW-1639: update modules

---

api/src/main/java/org/openmrs/module/pihmalawi/PihMalawiConstants.java
omod/src/main/java/org/openmrs/module/pihmalawi/PublicKeyProvider.java
omod/src/main/java/org/openmrs/module/pihmalawi/RestUtils.java
omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/DownloadDbRestController.java
omod/src/main/java/org/openmrs/module/pihmalawi/rest/controller/RegisterChildServerRestController.java
pom.xml

@mseaton , I have added more details about this process to the JIRA ticket, https://pihemr.atlassian.net/browse/MLW-1643

MLW-1643: add digital signature verification to REST request
